# Generated by Django 3.0 on 2021-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='dominant_hand_mode',
            field=models.TextField(blank=True, db_column='DominantHandMode', null=True),
        ),
    ]
