# Generated by Django 3.0 on 2021-02-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('component_type_id', models.AutoField(db_column='ComponentTypeId', primary_key=True, serialize=False)),
                ('component_type', models.CharField(db_column='ComponentType', max_length=50)),
            ],
            options={
                'db_table': 'ComponentType',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='language_id',
        ),
        migrations.AddField(
            model_name='taskcomponent',
            name='label',
            field=models.CharField(db_column='Label', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taskcomponent',
            name='order_key',
            field=models.IntegerField(db_column='OrderKey', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='components',
            field=models.ManyToManyField(to='rtl_ltr.TaskComponent'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcomponent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='taskcomponent',
            name='component_id',
        ),
        migrations.AddField(
            model_name='taskcomponent',
            name='component_type_id',
            field=models.ForeignKey(db_column='ComponentTypeId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.ComponentType'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Component',
        ),
    ]
