# Generated by Django 3.0 on 2021-03-09 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('proficiency_id', models.AutoField(db_column='ProficiencyId', primary_key=True, serialize=False)),
                ('proficiency_description', models.TextField(db_column='ProficiencyDescription')),
            ],
            options={
                'db_table': 'Proficiency',
            },
        ),
        migrations.RemoveField(
            model_name='participantlanguageproficiency',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='participantlanguageproficiency',
            name='proficiency_id',
            field=models.ForeignKey(db_column='ProficiencyId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.Proficiency'),
            preserve_default=False,
        ),
    ]
