# Generated by Django 3.1.7 on 2021-03-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='dominant_hand_web',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='hci_experience',
        ),
        migrations.AddField(
            model_name='participant',
            name='dominant_hand_mouse',
            field=models.CharField(db_column='DominantHandMouse', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_hci_experience',
            field=models.BooleanField(db_column='IsHciExperience', null=True),
        ),
    ]
