# Generated by Django 3.1.7 on 2021-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0002_auto_20210330_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireparticipant',
            name='questionnaire_finish',
            field=models.DateTimeField(db_column='QuestionnaireFinish', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireparticipant',
            name='questionnaire_start',
            field=models.DateTimeField(db_column='QuestionnaireStart'),
        ),
    ]
