# Generated by Django 3.0 on 2021-03-09 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0002_auto_20210309_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='other_language_proficiency',
        ),
        migrations.AddField(
            model_name='participant',
            name='native_language',
            field=models.ForeignKey(db_column='NativeLanguage', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.Language'),
            preserve_default=False,
        ),
    ]
