# Generated by Django 3.0 on 2021-02-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0002_auto_20210223_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_id', models.AutoField(db_column='ComponentId', primary_key=True, serialize=False)),
                ('direction', models.CharField(db_column='Direction', max_length=10)),
                ('order_key', models.IntegerField(db_column='OrderKey')),
                ('label', models.CharField(db_column='Label', max_length=10000)),
                ('component_type_id', models.ForeignKey(db_column='ComponentTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.ComponentType')),
            ],
            options={
                'db_table': 'Component',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='components',
            field=models.ManyToManyField(related_name='TaskComponent', to='rtl_ltr.Component'),
        ),
        migrations.AlterField(
            model_name='taskcomponent',
            name='component_type_id',
            field=models.ForeignKey(db_column='ComponentTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.Component'),
        ),
    ]
