# Generated by Django 3.0 on 2021-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0003_auto_20210315_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_add_picture',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_direction',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_new_page',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_required',
        ),
        migrations.AddField(
            model_name='task',
            name='is_add_picture_setting',
            field=models.BooleanField(db_column='IsAddPictureSetting', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_direction_setting',
            field=models.BooleanField(db_column='IsDirectionSetting', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_new_page_setting',
            field=models.BooleanField(db_column='IsNewPageSetting', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_required_setting',
            field=models.BooleanField(db_column='IsRequiredSetting', default=0),
            preserve_default=False,
        ),
    ]
