# Generated by Django 3.1.7 on 2021-03-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0003_auto_20210330_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskparticipant',
            name='is_demographic',
            field=models.BooleanField(db_column='IsDemographic', default=False),
        ),
    ]
