# Generated by Django 3.0 on 2021-02-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0003_auto_20210223_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componenttype',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='taskcomponent',
            name='component_type_id',
        ),
        migrations.RemoveField(
            model_name='taskcomponent',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='taskcomponent',
            name='label',
        ),
        migrations.RemoveField(
            model_name='taskcomponent',
            name='order_key',
        ),
        migrations.AddField(
            model_name='componenttype',
            name='component_type_name',
            field=models.CharField(db_column='ComponentTypeName', default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcomponent',
            name='component_id',
            field=models.ForeignKey(db_column='ComponentId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.Component'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='label',
            field=models.CharField(blank=True, db_column='Label', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='components',
            field=models.ManyToManyField(through='rtl_ltr.TaskComponent', to='rtl_ltr.Component'),
        ),
    ]
