# Generated by Django 3.0 on 2021-03-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0004_auto_20210310_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='questionnaire_version',
        ),
        migrations.AddField(
            model_name='participant',
            name='questionnaire_language_version',
            field=models.ForeignKey(db_column='QuestionnaireLanguageVersion', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questionnaire_language_version', to='rtl_ltr.Language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='browser_type',
            field=models.CharField(blank=True, db_column='BrowserType', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dominant_hand_mobile',
            field=models.CharField(blank=True, db_column='DominantHandMobile', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dominant_hand_web',
            field=models.CharField(blank=True, db_column='DominantHandWeb', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dominant_hand_writing',
            field=models.CharField(blank=True, db_column='DominantHandWriting', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='native_language',
            field=models.ForeignKey(db_column='NativeLanguage', on_delete=django.db.models.deletion.DO_NOTHING, related_name='native_language', to='rtl_ltr.Language'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='operating_system',
            field=models.CharField(blank=True, db_column='OperatingSystem', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='other_language_working_characteristics',
            field=models.TextField(blank=True, db_column='OtherLanguageWorkingCharacteristics', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='sex',
            field=models.CharField(blank=True, db_column='Sex', max_length=50, null=True),
        ),
    ]
