# Generated by Django 3.1.7 on 2021-04-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0005_auto_20210401_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=True),
        ),
    ]
