# Generated by Django 3.1.7 on 2021-03-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0005_questionnaire_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_title',
        ),
    ]
