# Generated by Django 3.0 on 2021-03-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0005_auto_20210310_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('component_type_id', models.AutoField(db_column='ComponentTypeId', primary_key=True, serialize=False)),
                ('component_type', models.CharField(db_column='ComponentType', max_length=100)),
            ],
            options={
                'db_table': 'ComponentType',
            },
        ),
        migrations.RemoveField(
            model_name='taskcomponent',
            name='component_id',
        ),
        migrations.RemoveField(
            model_name='taskcomponent',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='components',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_content',
        ),
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.TextField(db_column='Value', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='direction',
            field=models.CharField(db_column='Direction', default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.TextField(blank=True, db_column='Label', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='order_key',
            field=models.IntegerField(db_column='OrderKey', default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='TaskComponent',
        ),
        migrations.AddField(
            model_name='task',
            name='component_type_id',
            field=models.ForeignKey(db_column='ComponentTypeId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.ComponentType'),
            preserve_default=False,
        ),
    ]
