# Generated by Django 3.1.7 on 2021-05-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0006_auto_20210401_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_direction_setting',
            field=models.TextField(db_column='IsDirectionSetting'),
        ),
    ]
