# Generated by Django 3.1.7 on 2021-03-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0006_remove_task_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_age_demo',
            field=models.BooleanField(db_column='IsAgeDemo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_daily_demo',
            field=models.BooleanField(db_column='IsDailyDemo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_design_demo',
            field=models.BooleanField(db_column='IsDesignDemo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_develop_demo',
            field=models.BooleanField(db_column='IsDevelopDemo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_hci_demo',
            field=models.BooleanField(db_column='IsHciDemo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_knowledge_demo',
            field=models.BooleanField(db_column='IsKnowledgeDemo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_mobile_demo',
            field=models.BooleanField(db_column='IsMobileDemo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_mouse_demo',
            field=models.BooleanField(db_column='IsMouseDemo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_native_demo',
            field=models.BooleanField(db_column='IsNativeDemo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_other_demo',
            field=models.BooleanField(db_column='IsOtherDemo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_writing_demo',
            field=models.BooleanField(db_column='IsWritingDemo', default=1),
            preserve_default=False,
        ),
    ]
