# Generated by Django 3.1.7 on 2021-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0007_auto_20210504_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireparticipant',
            name='questionnaire_start',
        ),
        migrations.AddField(
            model_name='questionnaireparticipant',
            name='test_started',
            field=models.DateTimeField(db_column='TestStarted', default='1970-01-01'),
            preserve_default=False,
        ),
    ]
