# Generated by Django 3.1.7 on 2021-03-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0007_auto_20210325_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('task_type_id', models.AutoField(db_column='TaskTypeId', primary_key=True, serialize=False)),
                ('task_type', models.TextField(db_column='TaskType')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_type_id',
            field=models.ForeignKey(db_column='TaskTypeId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.tasktype'),
            preserve_default=False,
        ),
    ]
