# Generated by Django 3.2.2 on 2021-05-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0008_auto_20210510_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='native_language',
            field=models.ForeignKey(db_column='NativeLanguage', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='native_language', to='rtl_ltr.language'),
        ),
    ]
