# Generated by Django 3.1.7 on 2021-03-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0008_auto_20210326_1631'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasktype',
            table='TaskType',
        ),
    ]
