# Generated by Django 3.2.2 on 2021-05-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0009_alter_participant_native_language'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='taskparticipant',
        #     name='component_type_id',
        #     field=models.ForeignKey(db_column='ComponentTypeId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.componenttype'),
        #     preserve_default=False,
        # ),
    ]
