# Generated by Django 3.1.7 on 2021-03-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0009_auto_20210326_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='task_type_id',
            field=models.ForeignKey(db_column='TaskTypeId', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.tasktype'),
            preserve_default=False,
        ),
    ]
