# Generated by Django 3.2.2 on 2021-05-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0017_answer_is_demographic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='sex',
        ),
    ]
