# Generated by Django 3.2.2 on 2021-06-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0018_remove_participant_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireparticipant',
            name='time_spent_seconds',
            field=models.FloatField(db_column='TimeSpentSeconds', null=True),
        ),
    ]
