# Generated by Django 3.2.2 on 2021-07-13 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtl_ltr', '0020_usersloginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(db_column='StudentId', primary_key=True, serialize=False)),
                ('passport_id', models.IntegerField(db_column='PassportId')),
                ('student_name', models.TextField(db_column='StudentName')),
                ('participant_id', models.ForeignKey(db_column='ParticipantId', on_delete=django.db.models.deletion.DO_NOTHING, to='rtl_ltr.participant')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
